sudo: false
language: python
python:
- '3.7'
- '3.8'
- '3.9'
env:
- PACKAGES="django>=2.1,<2.2"
- PACKAGES="django>=2.2,<2.3"
- PACKAGES="django>=3.0,<3.1"
- PACKAGES="django>=3.1,<3.2"
before_install:
- pip install codecov
install:
- pip install -U pip wheel
- pip install $PACKAGES -e .
script:
- coverage run --source=polymorphic_tree runtests.py
after_success:
- codecov
branches:
  only:
  - master
notifications:
  email:
    recipients:
    - travis@edoburu.nl
    on_success: never
    on_failure: always
  slack:
    secure: WWNa4MHf50AOybB+XW9UKXCk/9Q8r++Jc4xTdEib43rj4odH9wxIaTRrzAbbpo3EO2gYuLgq6mMbaIZPD5l2UmgSnyuIbeYAAKIQblT+8XMamtXwnSS5j9vfBXYdj54rTlh+jKwEMW/JiQKl+SQpfQ2v1NMvYO63m89Ev9vXvcU=
    on_success: never
    on_failure: always
